### ISSUE TITLE
Set TimeZone

### ISSUE THREAD

**Issue by gizur-ess-prabhat** [bunkat/later#10]
Is there a way to set timezone in this module? My server is on UTC but I have to use Europe/Stockholm timezone but I am unable to set it.

**Comment by memelet** [comment]
How can the above work if later uses `new Date` all over the place?

**Comment by bunkat** [comment]
As neverfox pointed out, date handling is defined in later.date.timezone.  It only uses `new Date` to convert between integers and Date objects, it uses custom functions to build any dates or compute values that are timezone dependent.  This is how it can switch between UTC and local time.

**Comment by memelet** [comment]
So if I redefine later.date.timezone as above, and set it to arbitrary timezone, then all of later will work as expected in that timezone? Regardless of the use `new Date` in places?

**Comment by memelet** [comment]
I did a quick spike using moment-timezone. That doesn't work because `later.date.next()` invokes `later.date.build` with a day number that runs into the next month. It seems js.Date deals with and returns the next month, but moment throws an error.
