### ISSUE TITLE
Any way of doing a recurring schedule with seconds? 

### ISSUE THREAD

**Issue by LucasSeveryn** [bunkat/later#102]
Ideal:
    var sched = later.parse.text('every 30 mins starting on the 15th min 20th sec')

Workaround (that doesn't work):
    var sched = later.parse.text('every 1800 sec on the 920th sec')

Any way of adding seconds to the recurring schedule that starts 15 min 20 sec past an hour and runs every 30 minutes?

**Comment by bunkat** [comment]
I think this is what you are looking for:

````
var sched = later.parse.text('every 30 mins starting on the 15th min on the 20th sec');
later.schedule(sched).next(5)
[
  Tue Jun 09 2015 12:15:20 GMT-0700 (Pacific Daylight Time),
  Tue Jun 09 2015 12:45:20 GMT-0700 (Pacific Daylight Time),
  Tue Jun 09 2015 13:15:20 GMT-0700 (Pacific Daylight Time),
  Tue Jun 09 2015 13:45:20 GMT-0700 (Pacific Daylight Time),
  Tue Jun 09 2015 14:15:20 GMT-0700 (Pacific Daylight Time)
]
````

**Comment by LucasSeveryn** [comment]
This is fantastic, thank you. The documentation is a bit lacking when it comes to adding seconds in.
