### ISSUE TITLE
What if a scheduled task takes longer than the interval?

### ISSUE THREAD

**Issue by cleancoderocker** [bunkat/later#104]
What happens when a scheduled (repetitive) task takes longer as the provided interval? For example let's say you have one single task that should run every 5 minutes. Let's also say that normally each task runs about 2 minutes. What happens if one task takes longer (without knowing before that it will)? Will the next scheduled task be delayed automatically?

I need something like this: 

1: 10:00 for 2 minutes --> everything ok
2: 10:05 for 2 minutes --> everything ok
3: 10:10 for 7 minutes --> to prevent two running tasks at the same time ...
4: 10:20 for 2 minutes --> ... this run should start 5 minutes later

**Comment by bunkat** [comment]
No, you will need to handle this logic in your application code.  Later simply produces a schedule based on the constraints provided, it really has no notion of tasks or task length.

**Comment by coffy** [comment]
Here is my approach to avoid start of task during execution of one already running.

    var schedule = later.parse.recur().every(5).minute();
    var _running = false;
    var timer = later.setInterval(executeJobs, schedule);

    function executeJobs(){
       if (!_running) {
         _running = true;
         customAsyncFunction(function(){
            _running = false;
         });
      }
    }
