### ISSUE TITLE
A bug (?) with occurrences (cron parser)

### ISSUE THREAD

**Issue by anatskiy** [bunkat/later#107]
Supposing I have the following cron schedule:
```javascript
var schedule = later.parse.cron('* */4,16,18-20 * * *')
```
And I want to get 150 next occurrences:
```javascript
later.schedule(schedule).next(150)
```
As a result, I don't see any hours in range 18-20:
![screen shot 2015-07-06 at 12 53 04](https://cloud.githubusercontent.com/assets/7281783/8519795/00282768-23de-11e5-961d-688434cd4876.png)

Why is it so? Is it a bug or something else?

**Comment by bunkat** [comment]
Can you do a `console.log(schedule)`?

**Comment by anatskiy** [comment]
@bunkat, sure:

![screen shot 2015-07-06 at 21 34 48](https://cloud.githubusercontent.com/assets/7281783/8529990/f079b9a0-2426-11e5-8150-ec5d33f0da9a.png)

As I can guess, the parser worked out correctly. However, occurrences are not full.

**Comment by bunkat** [comment]
The values in `h` aren't sorted which the scheduler requires.  If you sort `h` numerically then it should work as expected.  Not sure why your cron statement resulted in unsorted values, but that is definitely the bug.

**Comment by anatskiy** [comment]
@bunkat, oh... ok, will wait for a fix. Till then I'll make some sort of a kludge :) 
Anyway, thank you for your awesome work!
