### ISSUE TITLE
Expected a conditional expression instead saw an assignment

### ISSUE THREAD

**Issue by m-menon** [bunkat/later#110]
Thanks for the library. It's been very useful. I was looking at the code and thought I should highlight one of the things I saw in the source. I am not too experienced in javascript but i think something is wrong with the If statement
it is one line 642
Expected a conditional expression instead saw an assignment. Is it missing another equal to operator?

thanks

![untitled](https://cloud.githubusercontent.com/assets/10776430/9429007/23f48fa6-49f4-11e5-8a8e-2c8f26bf4f5b.png)

**Comment by bunkat** [comment]
It's a code convention that isn't a best practice, but there is nothing wrong with the statement.  `end` gets assigned a new value which is then checked for existence by the if statement.

**Comment by m-menon** [comment]
cool...thank you :-)
