### ISSUE TITLE
setInterval throwing Invalid start date error

### ISSUE THREAD

**Issue by RaceProUK** [bunkat/later#111]
This is how I'm setting up the schedule:
```
const sched = later.parse.recur()
    .on(hours).hour()
    .on(minutes).minute();
later.setInterval(fn, sched);
```
But when I run our unit test suite, it throws `Error: Invalid start date.`
I've tried it using the text parser as well with a string like `at 00:00`, but the same error occurs.

I'm thinking either I've missed something important, or there's a weird issue I'm hitting.

**Comment by RaceProUK** [comment]
I think I've found the culprit: `later.js` line 633. When the `startDate` parameter is falsy, it gets set to the Unix epoch; the subsequent call to `getTime()` is therefore zero. And since JS treats zero as falsy, it fails the check and throws.

There are two other places that are affected: `later-core.js` line 633 and `src/core/schedule.js` line 52.

**Comment by bunkat** [comment]
I'm not sure how you are running into this as an issue.  If `startDate` is null, then it will use the current date as the start date.  If you pass in valid date (or value > 0) then it will use that date.  The only error case would be if you passed in `new Date(0)`  but it doesn't look like that is what you are doing.  Could you provide the full test case that is failing for you?

**Comment by RaceProUK** [comment]
It's an odd interaction between `later` and `sinon`'s fake timers; when I turned the fake timers off, the issue disappeared

**Comment by bunkat** [comment]
I don't use `sinon` so I probably won't attempt to fix this since turning off the fake timers fixes the issue.

**Comment by RaceProUK** [comment]
PR #112 has the fix needed; all you needed to do was click a button. But if you're happy leaving a bug in that is going to hit a lot of people just because you don't use something, then who am I to argue?

**Comment by bunkat** [comment]
The PR may fix this problem, but it's not clear what the root cause was.  Also, I make assumptions about falsy get time values all over the place so I'm not sure if this fixes all scenarios.

If you know exactly what it is about `sinon` fake timers that are causing the issue I'd be more inclined to take a fix. Then I would need additional test cases to go with the PR showing that the PR does in fact fix the problem (i.e. they should fail without the fix) when in use with `sinon`.
