### ISSUE TITLE
v1.1.8 is broken

### ISSUE THREAD

**Issue by scott113341** [bunkat/later#117]
```
$ node
> var later = require('later');
undefined
> later
{}
> later.parse
undefined
> later.parse.cron()
TypeError: Cannot read property 'cron' of undefined
    at repl:1:12
    at REPLServer.defaultEval (repl.js:132:27)
    at bound (domain.js:254:14)
    at REPLServer.runBound [as eval] (domain.js:267:12)
    at REPLServer.<anonymous> (repl.js:279:12)
    at REPLServer.emit (events.js:107:17)
    at REPLServer.Interface._onLine (readline.js:214:10)
    at REPLServer.Interface._line (readline.js:553:8)
    at REPLServer.Interface._ttyWrite (readline.js:830:14)
    at ReadStream.onkeypress (readline.js:109:10)
> 
```

```
$ npm list | grep later
├── later@1.1.8
```

:)

**Comment by bunkat** [comment]
Fixed in 1.1.9.

**Comment by QuantumInformation** [comment]
I just downloaded this for a react native project  but when running I get this:

![image](https://cloud.githubusercontent.com/assets/216566/11452047/6115f748-95d1-11e5-8073-27ef2ba62dfb.png)

var later = require('later');

**Comment by bunkat** [comment]
I'm not sure.  I just installed it from npm, created a test `index.js` file and it was able to find the module without a problem.  Does react native need something special?

**Comment by QuantumInformation** [comment]
I have this:
```
{
  "name": "reactNativeCron",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start"
  },
  "dependencies": {
    "later": "^1.2.0",
    "react-native": "^0.15.0"
  }
}
```

Just fired it up again in xCode and have same error, don't get it, the main points to index.js in later and exports the module.


My other requires work:
![image](https://cloud.githubusercontent.com/assets/216566/11456453/5056a3c0-9681-11e5-80c4-690fc22f0e51.png)

**Comment by bunkat** [comment]
Were you ever able to resolve this?

**Comment by danielgary** [comment]
I'm still seeing this issue.  Was there a workaround?

**Comment by rravikot** [comment]
+1

**Comment by danielgary** [comment]
For now I'm just including later as a static js file.
