### ISSUE TITLE
Using setTimeout with one time event no longer works

### ISSUE THREAD

**Issue by nmccann** [bunkat/later#119]
Hi,

I recently noticed that one time events were no longer being executed, and eventually narrowed it down to the following this https://github.com/bunkat/later/commit/5dcecba767f161682875424cd936d024c72ded27 

The `scheduleTimeout` function seems to return early if there is no next occurrence (seems related to https://github.com/bunkat/later/pull/103/). Is this intentional?

An example of my schedule: `Later.parse.recur().on(localDate.toDate()).fullDate()`

I added an example of a failing test to a my fork: https://github.com/nmccann/later/commit/e509ee9e1d0fd688d57da7677989f109b13799f7

I would also like to say thank you for the wonderful library, and I'm happy to see you're updating it again :)

Sidenote: When I'm running tests on the latest commit, it just says `10 passing (44ms)`, but on previous commits it would say `41709 passing (16s) 1 pending`. I put a `console.log` in one of the tests but it didn't show up. It seems like its skipping some tests.

**Comment by bunkat** [comment]
Sorry about that, I think it should be fixed now (and thanks for the test case!).  I'm glad that you find the library useful and appreciate the kind words.  I consider this library pretty much done, so I doubt you'll see any big changes but I will continue to fix any bugs as they crop up.

**Comment by nmccann** [comment]
Awesome, thank you for the quick response and fix!
