### ISSUE TITLE
Dawn/Dusk?

### ISSUE THREAD

**Issue by TotallyInformation** [bunkat/later#120]
Hi, is there any easy way to incorporate dawn/dusk into a schedule?

For example, if I want to trigger something 3 hours before dusk or 30 minutes after dawn.

Of course dawn/dusk is generally calculated based on latitude/longitude so some way of defining these is also required.

I need this for an IoT/Home Automation project & it would be great not to have to call out to another library.

**Comment by bunkat** [comment]
There is an example of creating a custom time period at http://bunkat.github.io/later/time-periods.html#custom.  I would need to think about the best way to create a dawn/dusk time period which unfortunately I don't have time to do at the moment, but it definitely should be possible (though 'easy' might be up for debate).
