### ISSUE TITLE
Subsecond Scheduling

### ISSUE THREAD

**Issue by dcurletti** [bunkat/later#122]
Is it possible to have Later.js create a schedule that fires at the START of every second?  I use later.js to schedule jobs that require them to start at the beginning of every second, so I was hoping there was a way to achieve this.

Thanks!

**Comment by bunkat** [comment]
Laterjs really wasn't designed to be a high performance job scheduler, it was designed for tasks at a more human scale. That being said, it does support second time intervals so a schedule like 'every 1 second'  would do what you want.

**Comment by dcurletti** [comment]
Ok I will look into it further, but from what I've experienced so far, if I want to start the job at 1443454617500, it will actually start at 1443454617564 (or some other non-perfect millisecond number) and still think it fired correctly because all it looked at was the fifth second.  I will post again with detailed examples.

**Comment by bunkat** [comment]
That's correct, it never attempts to be millisecond accurate.  The smallest resolution it supports is seconds.  If you need millisecond accuracy then you'll definitely want to use an actual job scheduler and not Later.js.

**Comment by dcurletti** [comment]
Forgot to respond at the time, but thank you for answering my question.
