### ISSUE TITLE
Text Parser

### ISSUE THREAD

**Issue by scgrant327** [bunkat/later#123]
I am trying to calculate complex dates with Later.js.

I want to to things like: "on the third Tuesday of every month"

But I get an error pointing to 'third'. According to the docs, only 'first' and 'last' are recoginzed...ok, so if I change it to: "on the first Tuesday of every month"

Then the error is at 'Tuesday'.

How I can use Later.js to figure such dates using the text parser?

**Comment by bunkat** [comment]
You're looking for `on Tuesday on the 3rd day instance`.  With Later, each constraint is specified separately so in this case you have a day constraint (`on Tuesday` - it only occurs when day of week is Tuesday) and a day instance constraint (`on the 3rd day instance` - it only occurs on the third occurrence of a day within a month).

**Comment by scgrant327** [comment]
Makes sense. I can get that to work, but how about if I want to do:
"on Saturday on the first day instance every 2 months starting 2/1/2016"

When I try that, the dates output are:
10/3/2015, 12:00:00 AM
12/5/2015, 12:00:00 AM
2/6/2016, 12:00:00 AM...

Shouldn't the first date be the February date? Or am I doing something wrong?

**Comment by bunkat** [comment]
If you want to start looking for occurrences after a particular date, pass the date to `next` instead of trying to embed it in the schedule definition.

````
// sched for minute equal to 1,2, or 3
  var sched = later.schedule(later.parse.recur().on(1,2,3).minute()),
      start = new Date('2013-05-22T10:22:00Z');

  // get the next instance
  sched.next(1, start);
  --> Mon, 22 May 2013 11:01:00 GMT
````

**Comment by scgrant327** [comment]
Got it. Thanks!

**Comment by scgrant327** [comment]
And how do I enter time ranges with the text parser?
Say I want:

"on Saturday on the first day instance every 2 months from 12:00 until 14:00"
