### ISSUE TITLE
Text Parsing #2

### ISSUE THREAD

**Issue by scgrant327** [bunkat/later#124]
How do I enter time ranges with the text parser?
Say I want:

"on Saturday on the first day instance every 2 months from 12:00 until 14:00"

**Comment by bunkat** [comment]
You can use the 'after' and 'before' keywords.  

```
after 12:00 before 14:00
````

Note that if you don't specify a recurrence (every 1 hour or something), every minute between those times would be considered valid.

**Comment by scgrant327** [comment]
Thanks again!
