### ISSUE TITLE
support @keywords in cron expressions

### ISSUE THREAD

**Issue by pekeler** [bunkat/later#125]
Would be great if keywords such as @daily and @hourly were supported.

https://en.wikipedia.org/wiki/Cron#Nonstandard_predefined_scheduling_definitions

**Comment by pekeler** [comment]
Seems that the old PR #45 adds support for these keywords.

**Comment by pekeler** [comment]
I hope this alternative PR #126 is acceptable.

**Comment by bunkat** [comment]
Thanks! Didn't seem like many people needed this so I wasn't going to bother implementing this, but your implementation was nice and clean so I went ahead and merged it.

**Comment by pekeler** [comment]
Thanks :)
