### ISSUE TITLE
every 10 days of the year starting on the 65th day of the year

### ISSUE THREAD

**Issue by gautaz** [bunkat/later#130]
Hello,

Looking at the laterjs text parser, I was wondering why the rank regex was limited to 59.
In fact, it makes sense for all time units but for days in the year.
Is there any particular reason for this ?

**Comment by bunkat** [comment]
Nope, that is definitely an oversight.  You're right that it should go up to 366 to cover all cases.

**Comment by gautaz** [comment]
OK, actually there is a way to work around the issue with:
`every 10 days of the year starting on the 0300 day of the year`

**Comment by gautaz** [comment]
Or to get back to the original example:
`every 10 days of the year starting on the 0065 day of the year`
But it seems a bit awkward...

**Comment by gautaz** [comment]
Fixing this with a regex that checks english grammar seems overwhelming, perhaps:
```javascript
/^((\d+)(st|nd|rd|th)?)\b/
```
would be enough for checking a rank?
If the user is not using the right cardinality suffix, I guess laterjs will still work as expected?

**Comment by bunkat** [comment]
Yes, this should work just fine.  Laterjs just strips the suffix anyways so it isn't important that it is correct and I wasn't doing all of the checks that would have been required to make sure that the value provided was actually valid anyways.

**Comment by gautaz** [comment]
Sorry for the delay,
@bunkat Do you want me to do a PR for this?

**Comment by bunkat** [comment]
If you want to, that would be great.  Thanks!

**Comment by gautaz** [comment]
Done :-). There is only one additional test case (two in fact for the day of year restriction), perhaps a few more would help...
