### ISSUE TITLE
Schedule unparser?

### ISSUE THREAD

**Issue by downie** [bunkat/later#135]
I'm looking for a way to generate cron and human-readable recurring strings programmatically. This library looks like a great solution for parsing those kinds of strings into its own internal schedule object but I don't see a means of getting that out. 

I want to do something like this:

```
var sched = later.parse.recur().on(2).minute();

var cron = sched.toCron(); // * * * * 2
var human = sched.toText(); // "on the 2nd minute"
```

The output would be the exact inverse of their respective parse methods, so if I did something like:
```
var sched2 = later.parse.cron(cron);
var sched3 = later.parse.text(human);
```
then `sched` would be equivalent to `sched2` and `sched3`.

Is this supported?

**Comment by bunkat** [comment]
That would be pretty neat, but definitely not something that is supported.

**Comment by downie** [comment]
Is that something you'd accept a PR for if I built it?

**Comment by bunkat** [comment]
Sure, I think I would prefer something like `later.schedule(sched).toCron()` and `later.schedule(sched).toText()` as the API.  Something like `sched.toCron()` doesn't really work since `sched` can just be a plain object.  If you made a separate component with tests and tied it into the API as described I would definitely accept it.

**Comment by downie** [comment]
Thanks for the advice! I may just do that. :)

**Comment by rravikot** [comment]
Has this been implemented? It would be a great feature to have.

**Comment by derekperkins** [comment]
We're in serious need of this too. @downie - have you made any progress?

@tannerlinsley

**Comment by downie** [comment]
@derekperkins No, I haven't. We changed priorities around so we didn't need that feature immediately, and then haven't had a strong enough need for it to go & build it yet. Sorry.

**Comment by qrpike** [comment]
+1
