### ISSUE TITLE
How to declare multiple holidays with time

### ISSUE THREAD

**Issue by pawarvijay** [bunkat/later#136]
**Multiple holidays**
holiday 1 :  every Monday from 8:00 am to 12:00 am = 16 hours
holiday 2 :  every Tuesday from 12:00 am to 8:00 am  = 8 hours

Or 

**Take it as long holiday**
starts at every Monday from 8:00 am & ends at  every Tuesday till 8:00 am  = 24 hours

**Comment by bunkat** [comment]
This will define a schedule for every 4 hours except during the holiday that you specified.

````
var sched = later.parse.recur()
    .every(4).hour()
    .except()
        .on(2).dayOfWeek().after('08:00').time()
    .and()
        .on(3).dayOfWeek().before('08:00').time();
````

**Comment by pawarvijay** [comment]
Your solution worked nicely also :+1:
