### ISSUE TITLE
Monthly recurring missed dates

### ISSUE THREAD

**Issue by c316** [bunkat/later#140]
How can I setup a monthly recurring schedule that won't miss any month? 

For instance if I record the first monthly started on January 30th I want the next one to be February 28th (except on leap years, which should land on February 29th). 

Thanks

**Comment by bunkat** [comment]
You can create composite schedules.  Here's one that will return the 30th of every month as well as the last day of February (whatever day that happens to be).

````
s = later.parse.recur().on(30).dayOfMonth().and().last().dayOfMonth().on(2).month(); 
````

**Comment by c316** [comment]
Thanks for the quick answer. February was just an example, but I see what you are getting at. 

So for the end result might look like this

   // Set dayOfMonth for schedule
    var dayOfMonth = 31;

    if(dayOfMonth === 31){
    s = later.parse.recur().on(31).dayOfMonth()
        .and().last().dayOfMonth()
        .on(2,4,6,9,11).month(); 
    } else if(dayOfMonth === 30){
        s = later.parse.recur().on(dayOfMonth).dayOfMonth()
        .and().last().dayOfMonth()
        .on(2).month(); 
    } else if(dayOfMonth === 29){
        s = later.parse.recur().on(dayOfMonth).dayOfMonth()
        .and().last().dayOfMonth()
        .on(2).month(); 
    }

Will the 29 section above cause the schedule to try to run twice on a leap year?

**Comment by bunkat** [comment]
For 31, you can just use `last().dayOfMonth()` since there are no months with more than 31 days.  The last schedule will not return multiple instances of the same date.  This will never happen with any schedule, a date either meets the constraints specified and is returned or it doesn't.  Dates are never checked multiple times against the same schedule.

**Comment by c316** [comment]
Thanks.
