### ISSUE TITLE
Run after today

### ISSUE THREAD

**Issue by c316** [bunkat/later#142]
Is there a simple way to setup a schedule that will not run today. I want to manually trigger a job when the user sets it up, then use later to run on the next scheduled occurrence. 

I have this now for weekly

```later.parse.text('at 12:00 pm on ' + dayOfWeek);```

and this for monthly when it lands on the 30th day of the month

```
later.parse.recur().on(dayOfMonth).dayOfMonth().on(12).hour()
.and().last().dayOfMonth().on(2).month().on(12).hour();
```

**Comment by bunkat** [comment]
When you go to calculate instances of the schedule using `later.schedule(s).next()` you can specify a date to start from.  

````
var s = later.parse.text('at 12:00 pm on ' + dayOfWeek);
later.schedule(s).next(10, new Date(...))
````

If you need the start date to be a part of the schedule, you can set up an exception schedule that excludes the current date.  It's generally a better idea not to hard code start and end dates in the schedule if you can help it.

**Comment by c316** [comment]
Thanks
