### ISSUE TITLE
How do I define a pattern + start date + end date / occurances

### ISSUE THREAD

**Issue by arnthorsnaer** [bunkat/later#144]
Hi there

I will be allowing users to define a schedule which will mimic many of the standard calendar recurrence functionality. 

So users will configure some recurrence pattern (supported by later.js), a start date. Then they will define a end date or alternatively they will define X number of occurrances.

I will be persisting this, and at first it seemed like it would suffice to persist the serialized schedule object which contains the defined schedule and exceptions. 

However I fail to figure out how I define a start date / end date or requested number of instances as a part of the schedule object? Perhaps this is not how is should work and I have to persist more than the schedule object.

Can anyone give me any hints?

**Comment by bunkat** [comment]
You were on the right track, you should store instance counts and start/end dates separately from the schedule object.  This is allows the same schedule object to work when the user decides to calculate instances across a different time period.

**Comment by arnthorsnaer** [comment]
Ok thanks. 

On a sidenote, given a start and end date can I get a count of the number of instances in-between the two?

**Comment by bunkat** [comment]
Just request a high number (like 1000000) of instances between the two dates, you'll get an array back of all the valid ones which you can then do a results.length on.  There is no way to get a count without actually calculating them all.

**Comment by arnthorsnaer** [comment]
Thanks dude!

**Comment by arnthorsnaer** [comment]
Correct me if I'm wrong, but this design makes "isValid()" useless in cases where I have instance count?

Currently in my code I use isValid to check the current date against my schedule to see if the date is valid. However if start / end dates exist outside the schedule then I have to see if the current date falls between the start and the end before calling isValid. 

Sure, that is not a big deal. However if I have a start date and X number of allowed instances, then I can't really use isValid() anymore. Instead I have to 1) see if the current date occurs on or after the start date and 2) generate X number of instances using next() and test each for equality with the current date (at least until the dates have gone beyond the current date). 

Not a big deal but I just wanted to see if this is correct before I start hacking :) 

-A

**Comment by bunkat** [comment]
You can check your date using isValid(), if it is false then you know it is not valid.  If it is true, then generate x instances from the start date.  Compare your date to the last instance generated.  If you date is <= to the last instance returned then you know it is valid and within the specified instance count. There is no need to test all the dates since isValid() has already indicated that you will find it.

**Comment by arnthorsnaer** [comment]
Thanks!
