### ISSUE TITLE
Uncaught Error: Definition must include at least one schedule.

### ISSUE THREAD

**Issue by fabiomig** [bunkat/later#148]
`var sched = {schedules: [
                          {h: [12], m: [08]},
                          {h: [17], m: [30]}
                        ]};
                        
var c       = new Date();
var month   = c.getMonth();
var year    = c.getFullYear();
var day     = c.getDay();
var hours   = c.getHours();
var minutes = c.getMinutes();

var teste = later.schedule(sched);

later.setInterval(function(){console.log(new Date());}, teste);`

what is wrong?

**Comment by bunkat** [comment]
You just need to pass in the JSON schedule object.

`later.setInterval(function(){console.log(new Date());}, sched);`
