### ISSUE TITLE
Insane values for string "every 24 hours"

### ISSUE THREAD

**Issue by robludwig** [bunkat/later#149]
I scheduled a process using later with the schedule `"every 24 hours"` to create a daily running task, and it never fired. I looked into the issue and found that later had parsed that to a rather insane schedule: The next occurrences is next year on Sun Jun 25 2017 19:59:00 GMT-0400 (EDT).

Changing the schedule to `"every day"` instead of `"every 24 hours"` solves the issue, but it was very tough bug to pin down.

Attached is some example code which should allow you to reproduce the issue:
```
"use strict";
var later = require('later');

var samples = [
  "every 24 hours at 12:00 am",
  "every 1 day at 12:00 am",
]

function printNextOccurrances(timeString){
  var sched = later.parse.text(timeString);
  var nextOccurs = later.schedule(sched).next(5);
  nextOccurs.forEach(function(occ){
    console.log(occ.toString());
  })
}

samples.forEach(function(sample){
  console.log("test schedule string\" " + sample + "\"");
  printNextOccurrances(sample);
  console.log("===================\n\n");
})
```

And the output:

> test schedule string" every 24 hours at 12:00 am"
> Sun Jun 25 2017 08:00:00 GMT-0400 (EDT)
> Wed Nov 07 2018 07:00:00 GMT-0500 (EST)
> Sat Mar 21 2020 08:00:00 GMT-0400 (EDT)
> Tue Aug 03 2021 08:00:00 GMT-0400 (EDT)
> Fri Dec 16 2022 07:00:00 GMT-0500 (EST)
> 
> test schedule string" every 1 day at 12:00 am"
> Fri Feb 12 2016 07:00:00 GMT-0500 (EST)
> Sat Feb 13 2016 07:00:00 GMT-0500 (EST)
> Sun Feb 14 2016 07:00:00 GMT-0500 (EST)
> Mon Feb 15 2016 07:00:00 GMT-0500 (EST)
> Tue Feb 16 2016 07:00:00 GMT-0500 (EST)
>

**Comment by bunkat** [comment]
Yes, you'll end up with funny schedules anytime you use invalid values with one of the time constraints.  The valid ranges for all built-in time constraints are documented, see http://bunkat.github.io/later/time-periods.html#hour for hours.  I can't really automatically filter out invalid values since before and after modifiers can take invalid values and make them valid.

**Comment by robludwig** [comment]
Agree that it's out of bounds for hours, however I would think that an exception would be thrown warning a developer that the value exceeds the possible hours.  Otherwise you can unknowingly end up in a situation, like we were, where later is scheduling your events for months in the future when you're expecting something to happen daily.

What about throwing an exception if the argument passed to the day/hour/minute parse functions exceeds the bounds? That way I have some warning instead of silently creating a schedule that doesn't make sense.

**Comment by bunkat** [comment]
It's not that simple.  All of the time periods are basically plugins that the core engine just has an interface for.  There is a call to check the extent of a time period (like for hours, it returns 0 to 23), however, this can be date dependent (think Feb, sometimes 29 is valid) and the engine doesn't know if a value is always invalid or just sometimes invalid.  There are also modifiers that can take invalid values and turn them into valid values.  So while you could try and cover things like day/hour/minute that really wouldn't solve the problem of catching schedules that don't do what you want them to do.

The best way is to just test the schedule that you create to make sure it is returning the dates you expect.

**Comment by markstos** [comment]
Even the "correct" sequence appears wrong here:

```
test schedule string" every 1 day at 12:00 am"
Fri Feb 12 2016 07:00:00 GMT-0500 (EST)
Sat Feb 13 2016 07:00:00 GMT-0500 (EST)
Sun Feb 14 2016 07:00:00 GMT-0500 (EST)
Mon Feb 15 2016 07:00:00 GMT-0500 (EST)
Tue Feb 16 2016 07:00:00 GMT-0500 (EST)
```

The test is running in UTC, where "12:00 AM" would be midnight. The results are output in Eastern Time, which is 5 hours earlier. So the resulting schedule should be recurring at 19:00 daily (24-5), but the parser is instead treating 12:00 AM as "Noon", and returning a sequence at 12-5 (7 AM Eastern) instead.

**Comment by markstos** [comment]
I've confirmed the noon-vs-midnight issue has recently been identified as a separate issue and there is  pull request pending for it on #188
