### ISSUE TITLE
How to serializable a schedule?

### ISSUE THREAD

**Issue by StarpTech** [bunkat/later#150]
"Schedules are simple json objects that are fully serializable. Easy and efficient to store in databases and in caches."

Where can I find a simple example or api documentation to serializable a schedule? For example serializable in JSON and from JSON.
Thank you.

**Comment by bunkat** [comment]
````
var sched = later.parse.text('every 5 mins');
console.log(sched);  // schedule is just plain JSON

let schedStr = JSON.stringify(sched);  // to string
let sched = JSON.parse(schedStr);  // back to schedule
````

**Comment by StarpTech** [comment]
Great @bunkat thank you!
