### ISSUE TITLE
How to accomplish 'Nth Wednesday'?

### ISSUE THREAD

**Issue by JulianKingman** [bunkat/later#151]
I'm wondering how to accomplish '1st and 3rd Wednesday of the month' in later or cron. Thx!

**Comment by bunkat** [comment]
You're looking for the day of week count constraint (http://bunkat.github.io/later/time-periods.html#day-of-week-count).

Here is one example using the text parser:

```
var sched = later.parse.text('on Wed on the 1st,3rd day instance');
later.schedule(sched).next(10);
```

**Comment by JulianKingman** [comment]
Thank you Bill!
