### ISSUE TITLE
every 2 week

### ISSUE THREAD

**Issue by Grandiz** [bunkat/later#156]
hello. found some issue with every N week.
```javascript
var shedule = later.parse.text('every 2 week on monday, friday starting on the 1 day of the year');
console.log( later.schedule(shedule).next(10) );
```
today is Wed Apr 06. I expect that the very first shedule will be at Fri Apr 08, but console.log says Mon Apr 11.

why does this happens and how to fix it?

**Comment by bunkat** [comment]
Later is a deterministic scheduler which means the schedules it calculates do not depend on the start date.  When you specify 'every N week' you are specifying 'every Nth week of the month' and not 'every N weeks from now'.  This is used if you wanted to schedule something on the 2nd Tuesday of every month for example.
