### ISSUE TITLE
Error "Invalid start date" for date 1970-01-01T00:00:00Z

### ISSUE THREAD

**Issue by themaarten** [bunkat/later#160]
When using `new Date('1970-01-01T00:00:00Z')` as the start date in a call to `schedule.next` (or its friends `prev`, `nextRange`, and `prevRange`), the method will throw `Error: Invalid start date`.

If the condition `!startDate.getTime()` at [schedule.js line 52](https://github.com/bunkat/later/blob/master/src/core/schedule.js#L52) is meant to check whether the date is valid, it should be `Number.isNaN(startDate.getTime())` instead of for checking for falsyness.

**Comment by bunkat** [comment]
I use this as a short cut in a bunch of places to eek out a little bit of performance.  The case of needing to start at the epoch is uncommon and not supported.

**Comment by themaarten** [comment]
The performance gain of using `!x` instead of `Number.isNaN(x)` should be in the order of nanoseconds, if there is a gain at all. In my opinion, this micro-optimization does not justify sacrificing correctness. 

Starting at the epoch might actually be more common than you'd think. I ran into this issue because I used [sinon.useFakeTimers()](http://sinonjs.org/docs/#clock) in my tests. Sinon's fake time starts at the UNIX epoch by default.

At the very least, not supporting the UNIX epoch as start date should be documented. It could save others a lot of debugging time in the future.

**Comment by bunkat** [comment]
It's not just that one check, it means that I never have to track the epoch as a valid occurrence which does have an impact (less garbage). In my case I needed to calculate 10s of thousands of schedules and so every little bit helped (though it definitely could be optimized further). 

I guess it could be documented more clearly, but it did throw an error telling you that the start date was not valid.
