### ISSUE TITLE
Possible issues on text parser (every X hours) 

### ISSUE THREAD

**Issue by Alex-Werner** [bunkat/later#185]
Hi, 

I'm not sure if I didn't write something wrong, but here is my problem using node and  "later": "^1.2.0",: 

I've set a stuff (job) to be executed every 10 hours. 
I launch my node at  12 October 15:25, (13:25 in ISODate) and expected to my schedule to be executed at :
12Oct : 23Z,
13Oct: 9Z, 19Z
14Oct : 5Z, 15Z, etc...

But console.log out the next 15 occurs of my scheduleParsed I got this : 

12Oct: 18Z (so 5 hours after launch ? ), 22Z (huh ?),
13Oct : 8Z , 18Z, 22Z
14Oct: 8Z, 18Z, 22Z 
Etc.... 

![image](https://cloud.githubusercontent.com/assets/5849920/19311953/b087e556-9090-11e6-9adf-ac09ebf2de33.png)

```
var job = { name:"A name",schedule:'every 10 hours', execute:function(){console.log('stuff')}}
var textSchedule = job.schedule;
var scheduleParsed = Later.parse.text(textSchedule);
var fnToExec = job.execute;
var timer = Later.setInterval(fnToExec, scheduleParsed);

console.log(job);
console.log('Time now', new Date().toISOString());
console.log(job.name,Later.schedule(scheduleParsed).next(15));
```

**Comment by Alex-Werner** [comment]
A deeper look into test files, into this issues : https://github.com/bunkat/later/issues/109 and some other looks, made me tell that there might be not a bug.
I've got a wrong understanding about what later do.

**Comment by bunkat** [comment]
Yep, it's a common misconception.  I've meant to update the docs at some point but haven't gotten around to it.
