### ISSUE TITLE
Documentation source available?

### ISSUE THREAD

**Issue by barrettc** [bunkat/later#234]
Thanks for the great library. I'm wondering if it's possible to make the documentation repo available? I have some changes I'm planning in a fork and would love to have the docs on bunkat.github.io as a starting point as well.

Thanks

**Comment by zxc122333** [comment]
https://github.com/bunkat/later/tree/gh-pages

**Comment by barrettc** [comment]
Oh duh... thanks, now I feel dumb. :)
