### ISSUE TITLE
create a git tag in order to define propper bower dependency

### ISSUE THREAD

**Issue by olegomon** [bunkat/later#53]
At the moment it is not possible to define a bower dependency with a specific version. It is not obvious which version is used by the project.

**Comment by yzarubin** [comment]
Bump, this is desperately needed.

**Comment by xorgy** [comment]
@bunkat

In order for specific releases to be installed (by bower at least), there needs to be a tag with a matching name in the git repository.

You can add a release tag for the current release `1.1.6` by running `git tag 1.1.6`, and then pushing to master using `git push --tags`.

This operation requires direct access, and sadly can't be done by pull request.

Thanks for caring. `:-)`

**Comment by bunkat** [comment]
1.1.7 should be properly tagged now.
