### ISSUE TITLE
Add method strip() to schedules so users don't have to do it manually

### ISSUE THREAD

**Issue by matthewadams** [bunkat/later#55]
The documentation at http://bunkat.github.io/later/parsers.html#recur says that users should strip their schedule of methods before serialization.  If one of the methods that's added to a schedule were ```strip()```, encapsulating the logic required, then it'd be simpler for the user to do that.  With the proposed method,
```
var s = {schedules: sched.schedules, exceptions: sched.exceptions};
```
becomes
```
var s = sched.strip();
```

**Comment by bunkat** [comment]
I don't think this is actually needed.  Most serialization methods (such as JSON.stringify) already automatically strip the function calls and other then that they don't really add any overhead. The note in the documentation was more just to make people aware that there will be additional properties on the schedule.
