### ISSUE TITLE
(not a issue) a question...regarding updating schedules

### ISSUE THREAD

**Issue by pateljatin** [bunkat/later#84]
Hi,

Is there a way to update or add to an existing job/schedule?
For example:
```
var s = later.parse.recur().on(periodsArray)
					.time()
					.before(later.dayWithTime.end(endDate)).fullDate();
var interId = later.setInterval(function() { 
    doSomethingFunc(myVal); 
}, s);
```
Is there a way to add more to interId midstream? or update it?  

Thanks,
JP

**Comment by bunkat** [comment]
You'll just want to cancel the existing one (using `interId.clear()` in your case), update your schedule or function and then restart the interval.  While you probably could just update the underlying schedule, if new schedule has a valid occurrence before the old schedule, you will miss that occurrence.
