### ISSUE TITLE
fractional parts of a period

### ISSUE THREAD

**Issue by timcullen** [bunkat/later#91]
Is it possible to schedule events recurring at a fractional interval of a particular period (e.g. twice a month, twice a quarter).  Whilst this is likely to be a rare problem in practice, I do have a payroll application where semi-monthly (ie twice a month) is frequently used.  If not directly supported, I wonder if there's a way to do it by creating a custom period (days 1-15 being first half and 16 to end of month being second half)?

**Comment by bunkat** [comment]
Later supports all types of schedules.  You can schedule things for the 1st and 15th of a month, 2nd and last Tuesday, every 4 months on the 1st Tuesday, etc.  Check out the documentation at http://bunkat.github.io/later/parsers.html#recur to see what types of things are possible.
