### ISSUE TITLE
Calculate only the count of the next X dates

### ISSUE THREAD

**Issue by noamtz** [bunkat/later#94]
I need to get only the number of next X occurrences and not the dates itselfs.

    var start = /*Now*/;
    var end = /*Before 2 days from now*/;
    var s = later.parse.cron('* * * * * *');// every minutes
    later.schedule(s).prev(9999999, start, end);

In 1 day we have 1440 minutes so the above code will return 2880 previous dates (every minute for the last 2 days), actually it'll return only the last 999 dates. 

Is there a way to get only the number 2880 without to generate all the dates?

Thanks

**Comment by bunkat** [comment]
Currently no. You would need to modify the library if you need that functionality.
