### ISSUE TITLE
Calculating next with offset

### ISSUE THREAD

**Issue by osteenbergen** [bunkat/later#98]
### Use cases
- User wants to execute a job now and repeat it according to a schedule.
- Server executes tasks and wants to spread the load using creation time of the task. Multiple events fire at xx:xx:00 while none fire during the remaining 59 seconds
### Problem

Current time is 9:42 next run should happen at 9:52 followed by 10:02, but the following code returns 9:50 and 10:00. The start parameter is used to determine the closest date and not as a starting date.

``` javascript
var later = require("later");
var sched = later.parse.text("every 10 minutes");
later.schedule(sched).next(2, new Date())
```
### Suggested solution

Schedules can be very complex with irregular intervals but for the simple "every 2 hours" it could be implemented. 
For the first use-case something like the following would help:

``` javascript
later.schedule(sched).started_at(creation_date).next(2)
```

As the schedules contain arrays of minutes (or larger intervals) you could take at least the seconds from the creation_date. To reuse the minutes it requires some changes to the schedule object to store the pattern in the numbers (in this case 10) instead of the actual numbers. If you have the pattern you can do a modulo to get the offset you can use.

Adding precision to the calculation which would solve the second use-case:

``` javascript
sched.precision("minutes")
later.schedule(sched).next(2, new Date())
```

I guess the precision is easier to calculate and doesn't require a large change in how you store the schedule:

``` javascript
function precision(prec){
  var seconds = get_precision(prec);
  var offset = Math.floor(Math.random() * seconds)
  this.precision_offset = offset;
}

function next(count, start, end){
  // do normal calcuation
  var sched = this.sched;
  var results = super.map(function(time){
    time.setSeconds(t.getSeconds() + sched.precision_offset);
  });
  return results;
}
```

If I have some time I will try to build a pull request.

**Comment by bunkat** [comment]
The recur parser (see documentation at http://bunkat.github.io/later/parsers.html#recur) handles this via a `starting on` operation.  Basically it allows you to offset times so that lots of jobs don't all get kicked off at once which I think is similar to what you are trying to solve.

````
// fires on the 10th, 25th, 40th, and 55th minute of every hour
  later.parse.recur().every(15).minute().startingOn(10);
````

However, this modifies the core schedule that is produced.  I imagine if you wanted to be able to maintain a single schedule (without these types of offsets) you would just inject an additional constraint immediately before calculating the schedules.  For example, if you wanted to randomize which second a job was scheduled for you would take your existing schedule and add a new seconds constraint.

````
var sched = {schedules: [{m: [0, 15, 30, 45]}]}
sched.schedules.push({s: [Math.floor(Math.rand() * 59)]})
later.schedule(sched);
````

You would then execute the task at the next calculated execution time. This way you could distribute the tasks over whatever time period you were interested in.

**Comment by osteenbergen** [comment]
Thanks for the quick response! I have seen the startingOn, however it modifies the schedule like you said. Modifying the seconds would be similar to the precision solution i proposed, however adding a second schedule results in incorrect scheduling. Here is the output of your example:
```
[ Fri Apr 24 2015 11:28:24 GMT+0200 (CEST),
  Fri Apr 24 2015 11:29:24 GMT+0200 (CEST),
  Fri Apr 24 2015 11:30:00 GMT+0200 (CEST),
  Fri Apr 24 2015 11:30:24 GMT+0200 (CEST),
  Fri Apr 24 2015 11:31:24 GMT+0200 (CEST)]
```
It still fires at 30:00, but now also every minute at the random second as expected. So the solution is to either modify the schedule itself or introduce the fixed offset.

For my scheduling problem the user types the schedule using the text parser. The user will prefer simple schedules like "every 2 hours", however on a backend i must consider the load of every schedule firing at exact moments. I can solve the issue by introducing the offset in my backend, but I thought it would also be a nice addition to later itself.

**Comment by Josenzo** [comment]
I have the same problem. My server will run too many cron's but with later all the crons that are running each minute will be executed at the same time.
```javascript
console.log(new Date());
console.log('---------------')
var schule = later.parse.cron('* */10 * * * *', true);
console.log( later.schedule(schule).next(3) );
/*
Fri May 22 2015 18:04:45 GMT+0300 (EEST)
---------------
[ Fri May 22 2015 18:10:00 GMT+0300 (EEST),
  Fri May 22 2015 18:20:00 GMT+0300 (EEST),
  Fri May 22 2015 18:30:00 GMT+0300 (EEST) ]
*/
```

The api provide any way to get a result like this?
```
[ Fri May 22 2015 18:14:45 GMT+0300 (EEST),
  Fri May 22 2015 18:24:45 GMT+0300 (EEST),
  Fri May 22 2015 18:34:45 GMT+0300 (EEST) ]
```

**Comment by osteenbergen** [comment]
closing as this is not maintained..
