### ISSUE TITLE
later run twice or more for first time 

### ISSUE THREAD

**Issue by mohamedmohsin** [bunkat/later#99]
Example:

var later = require('later');
var schedule=later.parse.text('every 1 mins');
later.date.localTime();

later.setInterval(function () {
	console.log(new Date());
}, schedule);

my Output:

Wed May 06 2015 08:46:59 GMT+0530 (India Standard Time)
Wed May 06 2015 08:46:59 GMT+0530 (India Standard Time)
Wed May 06 2015 08:47:00 GMT+0530 (India Standard Time)

but expected
 
Wed May 06 2015 08:47:00 GMT+0530 (India Standard Time)

**Comment by bunkat** [comment]
This is discussed in detail in issue #90.  I haven't gotten a chance to patch `setInterval` yet but there are some thoughts in the thread about how to go about doing it.
